version: '3.8'
  
services:
  

  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: P@ssw0rd
      MSSQL_PID: Express

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672 
    environment:
        RABBITMQ_DEFAULT_USER: guest 
        RABBITMQ_DEFAULT_PASS: guest

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300

  server:
    image: nginxdemos/hello
    ports: 
      - 80

  localtunnel:
    image: efrecon/localtunnel
    restart: on-failure
    command:
      --local-host server --port 80 --subdomain $SUBDOMAIN
    environment: 
      - SUBDOMAIN=mihomiue
    links:
      - server
    depends_on:
      - server